mybatis:
  type-aliases-package: cn.mutun.prodriverhelper_exam.Entity

spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: dbcp1
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/predriverhelper?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 1234

debug: true
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  notEmpty: true



